import {LangCode, LanguageMeta} from "./types";

export const LANGUAGES: Record<LangCode, LanguageMeta> = {
	AR: { code: 'AR', name: 'Arabic', script: 'other' },
	BG: { code: 'BG', name: 'Bulgarian', script: 'cyrillic' },
	CS: { code: 'CS', name: 'Czech', script: 'latin' },
	DA: { code: 'DA', name: 'Danish', script: 'latin' },
	DE: { code: 'DE', name: 'German', script: 'latin' },
	EL: { code: 'EL', name: 'Greek', script: 'other' },
	EN: { code: 'EN', name: 'English', script: 'latin' },
	ES: { code: 'ES', name: 'Spanish', script: 'latin' },
	ET: { code: 'ET', name: 'Estonian', script: 'latin' },
	FI: { code: 'FI', name: 'Finnish', script: 'latin' },
	FR: { code: 'FR', name: 'French', script: 'latin' },
	HE: { code: 'HE', name: 'Hebrew', script: 'other' },
	HU: { code: 'HU', name: 'Hungarian', script: 'latin' },
	ID: { code: 'ID', name: 'Indonesian', script: 'latin' },
	IT: { code: 'IT', name: 'Italian', script: 'latin' },
	JA: { code: 'JA', name: 'Japanese', script: 'other' },
	KO: { code: 'KO', name: 'Korean', script: 'other' },
	LT: { code: 'LT', name: 'Lithuanian', script: 'latin' },
	LV: { code: 'LV', name: 'Latvian', script: 'latin' },
	NB: { code: 'NB', name: 'Norwegian Bokmål', script: 'latin' },
	NL: { code: 'NL', name: 'Dutch', script: 'latin' },
	PL: { code: 'PL', name: 'Polish', script: 'latin' },
	PT: { code: 'PT', name: 'Portuguese', script: 'latin' },
	RO: { code: 'RO', name: 'Romanian', script: 'latin' },
	SK: { code: 'SK', name: 'Slovak', script: 'latin' },
	SL: { code: 'SL', name: 'Slovenian', script: 'latin' },
	SV: { code: 'SV', name: 'Swedish', script: 'latin' },
	TH: { code: 'TH', name: 'Thai', script: 'other' },
	TR: { code: 'TR', name: 'Turkish', script: 'latin' },
	UK: { code: 'UK', name: 'Ukrainian', script: 'cyrillic' },
	VI: { code: 'VI', name: 'Vietnamese', script: 'latin' },
	ZH: { code: 'ZH', name: 'Chinese', script: 'other' },
}
